export const PLAYER_PHOTOS = {
  'ezequiel unsain':        '/players/Ezequiel Unsain.jpg',
  'agustín oliveros':       '/players/Agustín Oliveros.jpg',
  'agustin oliveros':       '/players/Agustín Oliveros.jpg',
  'francisco méndez':       '/players/Francisco Méndez.jpg',
  'francisco mendez':       '/players/Francisco Méndez.jpg',
  'alexis peña':            '/players/Alexis Peña.jpg',
  'alexis pena':            '/players/Alexis Peña.jpg',
  'raúl martínez':          '/players/Raúl Martínez.jpg',
  'raul martinez':          '/players/Raúl Martínez.jpg',
  'emilio lara':            '/players/Emilio Lara.jpg',
  'ricardo alonso':         '/players/Ricardo Alonso.jpg',
  'cristian calderón':      '/players/Cristian Calderón.jpg',
  'cristian calderon':      '/players/Cristian Calderón.jpg',
  'daniel leyva':           '/players/Daniel Leyva.jpg',
  'kevin gutiérrez':        '/players/Kevin Gutiérrez.jpg',
  'kevin gutierrez':        '/players/Kevin Gutiérrez.jpg',
  'rogelio cortéz':         '/players/Rogelio Cortéz.jpg',
  'rogelio cortez':         '/players/Rogelio Cortéz.jpg',
  'agustín almendra':       '/players/Agustín Almendra.jpg',
  'agustin almendra':       '/players/Agustín Almendra.jpg',
  'israel tello':           '/players/Israel Tello.jpg',
  'franco rossano':         '/players/Franco Rossano.jpg',
  'ricardo monreal':        '/players/Ricardo Monreal.jpg',
  'kevin rosero':           '/players/Kevin Rosero.jpg',
  'javier ruiz':            '/players/Javier Ruiz.jpg',
  'lorenzo faravelli':      '/players/Lorenzo Faravelli.jpg',
  'julián carranza':        '/players/Julián Carranza.jpg',
  'julian carranza':        '/players/Julián Carranza.jpg',
  'tomás badaloni':         '/players/Tomás Badaloni.jpg',
  'tomas badaloni':         '/players/Tomás Badaloni.jpg',
  'bryan casas':            '/players/Bryan Casas.jpg',
}

export function getPlayerPhoto(name) {
  return PLAYER_PHOTOS[(name || '').toLowerCase().trim()] || null
}
